TebLocalPlannerROS:
  map_frame: jeeves/map_nn0
  min_obstacle_dist: 0.01
  inflation_dist: 0.1

  acc_lim_theta: 0.3
  max_vel_theta: 0.3
  acc_lim_x: 0.3
  max_vel_x: 0.3
  max_vel_x_backwards: 0.3
  weight_kinematics_forward_drive: 100

  dt_ref: 0.1
  dt_hysteresis: 0.01
  max_global_plan_lookahead_dist: -1

  enable_homotopy_class_planning: true
  enable_multithreading: true
  max_number_classes: 4

  footprint_model:
    type: polygon
    vertices: [[-0.25,-0.3],[0.83,-0.3],[0.83,0.34],[-0.25,0.34]]
