robot_base_frame: base_footprint
footprint: [[-0.5, -0.325], [0.7, -0.325], [0.7, 0.325], [-0.5, 0.325]]
publish_frequency: 30

laser_obstacles:
  observation_sources: right_front_rplidar_scan left_back_rplidar_scan
  track_unknown_space: true
  obstacle_range: 4.5
  raytrace_range: 5

  right_front_rplidar_scan:
    data_type: LaserScan
    expected_update_rate: 0
    clearing: true
    marking: true

  left_back_rplidar_scan:
    data_type: LaserScan
    expected_update_rate: 0
    clearing: true
    marking: true

rgdb_obstacles:
  enabled:                  true
  voxel_decay:              60
  decay_model:              0
  voxel_size:               0.05
  track_unknown_space:      true
  max_obstacle_height:      3.0
  unknown_threshold:        15
  mark_threshold:           0
  update_footprint_enabled: true
  combination_method:       1
  obstacle_range:           8.5
  origin_z:                 0.0
  publish_voxel_map:        true
  observation_sources:      realsense_mark realsense_clear

  realsense_mark:
    data_type: PointCloud2
    topic: realsense/depth/points
    marking: true
    clearing: false
    min_obstacle_height: 0.01
    max_obstacle_height: 3.0
    voxel_filter: true
    
  realsense_clear:
    data_type: PointCloud2
    topic: realsense/depth/points
    marking: false
    clearing: true
    min_z: 0.01
    max_z: 9.0
    vertical_fov_angle: 0.96
    horizontal_fov_angle: 1.22
    decay_acceleration: 5
    model_type: 0
