local_costmap:
  plugins:
    #- {name: laser_obstacles, type: 'costmap_2d::ObstacleLayer'}
    - {name: rgdb_obstacles, type: 'spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer'}

  rolling_window: true
  width: 6
  height: 6
  resolution: 0.05
